const WomenProducts = [
    { id: 1, name: 'Blossom Walk', price: 'Rs. 2500' , image: {shoe1: '/src/images/shoes-img/women/1-a.png',shoe2: '/src/images/shoes-img/women/1-b.png',shoe3: '/src/images/shoes-img/women/1-c.png'}, color: {shoe1: 'pink', shoe2: 'skin', shoe3: 'orange'} },
    { id: 2, name: 'Serene Step', price: 'Rs. 3599',  image: {shoe1: '/src/images/shoes-img/women/2-a.png',shoe2: '/src/images/shoes-img/women/2-b.png',shoe3: '/src/images/shoes-img/women/2-c.png'}, color: {shoe1: 'white-green', shoe2: 'white-purple', shoe3: 'white'} },
    { id: 3, name: "Luna Lace", price: 'Rs. 6599', image: {shoe1: '/src/images/shoes-img/women/3-a.png',shoe2: '/src/images/shoes-img/women/3-b.png',shoe3: '/src/images/shoes-img/women/3-c.png'}, color: {shoe1: 'white', shoe2: 'brown', shoe3: 'black'} },
    { id: 4, name: 'Radiant Stride', price: 'Rs. 7999', image: {shoe1: '/src/images/shoes-img/women/4-a.png',shoe2: '/src/images/shoes-img/women/4-b.png',shoe3: '/src/images/shoes-img/women/4-c.png'}, color: {shoe1: 'pink', shoe2: 'white', shoe3: 'blue'} },
    { id: 5, name: 'Enchant Walk', price: 'Rs. 3200', image: {shoe1: '/src/images/shoes-img/women/5-a.png',shoe2: '/src/images/shoes-img/women/5-b.png',shoe3: '/src/images/shoes-img/women/5-c.png'}, color: {shoe1: 'white-blue', shoe2: 'light-black', shoe3: 'white'} },
    { id: 6, name: 'Aurora Glide', price: 'Rs. 5299', image: {shoe1: '/src/images/shoes-img/women/6-a.png',shoe2: '/src/images/shoes-img/women/6-b.png',shoe3: '/src/images/shoes-img/women/6-c.png'}, color: {shoe1: 'pink', shoe2: 'blue', shoe3: 'white'} },
    { id: 7, name: 'Whisper Sole', price: 'Rs. 3999', image: {shoe1: '/src/images/shoes-img/women/7-a.png',shoe2: '/src/images/shoes-img/women/7-b.png',shoe3: '/src/images/shoes-img/women/7-c.png'}, color: {shoe1: 'light-purple', shoe2: 'white', shoe3: 'black'} },
    { id: 8, name: 'Ember Elevate', price: 'Rs. 999', image: {shoe1: '/src/images/shoes-img/women/8-a.png',shoe2: '/src/images/shoes-img/women/8-b.png',shoe3: '/src/images/shoes-img/women/8-c.png'}, color: {shoe1: 'white-black', shoe2: 'black-red', shoe3: 'blue'} },
    { id: 9, name: 'Pearl Petal', price: 'Rs. 2499', image: {shoe1: '/src/images/shoes-img/women/9-a.png',shoe2: '/src/images/shoes-img/women/9-b.png',shoe3: '/src/images/shoes-img/women/9-c.png'}, color: {shoe1: 'pink', shoe2: 'black', shoe3: 'white'} },
    { id: 10, name: 'Radiant Rise', price: 'Rs. 6500', image: {shoe1: '/src/images/shoes-img/women/10-a.png',shoe2: '/src/images/shoes-img/women/10-b.png',shoe3: '/src/images/shoes-img/women/10-c.png'}, color: {shoe1: 'orange', shoe2: 'purple', shoe3: 'pink'} },
    { id: 11, name: 'Velvet Vista', price: 'Rs. 8500', image: {shoe1: '/src/images/shoes-img/women/11-a.png',shoe2: '/src/images/shoes-img/women/11-b.png',shoe3: '/src/images/shoes-img/women/11-c.png'}, color: {shoe1: 'purple', shoe2: 'black', shoe3: 'white'} },
    { id: 12, name: 'Opal Orbit', price: 'Rs. 7599', image: {shoe1: '/src/images/shoes-img/women/12-a.png',shoe2: '/src/images/shoes-img/women/12-b.png',shoe3: '/src/images/shoes-img/women/12-c.png'}, color: {shoe1: 'pink', shoe2: 'black', shoe3: 'white'} },
    { id: 13, name: 'Willow Walk', price: 'Rs. 4800', image: {shoe1: '/src/images/shoes-img/women/13-a.png',shoe2: '/src/images/shoes-img/women/13-b.png',shoe3: '/src/images/shoes-img/women/13-c.png'}, color: {shoe1: 'white', shoe2: 'white', shoe3: 'white'} },
    { id: 14, name: 'Velvet Voyage', price: 'Rs. 5600', image: {shoe1: '/src/images/shoes-img/women/14-a.png',shoe2: '/src/images/shoes-img/women/14-b.png',shoe3: '/src/images/shoes-img/women/14-c.png'}, color: {shoe1: 'purple', shoe2: 'pink', shoe3: 'white'} },
    { id: 15, name: 'Petal Pulse', price: 'Rs. 3500', image: {shoe1: '/src/images/shoes-img/women/15-a.png',shoe2: '/src/images/shoes-img/women/15-b.png',shoe3: '/src/images/shoes-img/women/15-c.png'}, color: {shoe1: 'skyblue', shoe2: 'pink', shoe3: 'blue'} },
    { id: 16, name: 'Aurora Avenue', price: 'Rs. 2300', image: {shoe1: '/src/images/shoes-img/women/16-a.png',shoe2: '/src/images/shoes-img/women/16-b.png',shoe3: '/src/images/shoes-img/women/16-c.png'}, color: {shoe1: 'pink', shoe2: 'black', shoe3: 'white'} },
    { id: 17, name: 'Mystic Muse', price: 'Rs. 6999', image: {shoe1: '/src/images/shoes-img/women/17-a.png',shoe2: '/src/images/shoes-img/women/17-b.png',shoe3: '/src/images/shoes-img/women/17-c.png'}, color: {shoe1: 'brown', shoe2: 'white', shoe3: 'orange'} },
    { id: 18, name: 'Luna Luxe', price: 'Rs. 8900', image: {shoe1: '/src/images/shoes-img/women/18-a.png',shoe2: '/src/images/shoes-img/women/18-b.png',shoe3: '/src/images/shoes-img/women/18-c.png'}, color: {shoe1: 'green', shoe2: 'black', shoe3: 'black'} },
    { id: 19, name: 'Velvet Voyage', price: 'Rs. 7900', image: {shoe1: '/src/images/shoes-img/women/19-a.png',shoe2: '/src/images/shoes-img/women/19-b.png',shoe3: '/src/images/shoes-img/women/19-c.png'}, color: {shoe1: 'purple', shoe2: 'black', shoe3: 'black-pink'} },
    { id: 20, name: 'Aurora Astral', price: 'Rs. 5800', image: {shoe1: '/src/images/shoes-img/women/20-a.png',shoe2: '/src/images/shoes-img/women/20-b.png',shoe3: '/src/images/shoes-img/women/20-c.png'}, color: {shoe1: 'green', shoe2: 'pink', shoe3: 'white'} },
    { id: 21, name: 'Petal Pulse', price: 'Rs. 9999', image: {shoe1: '/src/images/shoes-img/women/21-a.png',shoe2: '/src/images/shoes-img/women/21-b.png',shoe3: '/src/images/shoes-img/women/21-c.png'}, color: {shoe1: 'skyblue', shoe2: 'black', shoe3: 'pink'} },
    { id: 22, name: 'Celestial', price: 'Rs. 8900', image: {shoe1: '/src/images/shoes-img/women/22-a.png',shoe2: '/src/images/shoes-img/women/22-b.png',shoe3: '/src/images/shoes-img/women/22-c.png'}, color: {shoe1: 'pink', shoe2: 'purple', shoe3: 'black'} },
    { id: 23, name: 'Radiant Rhythm', price: 'Rs. 7999', image: {shoe1: '/src/images/shoes-img/women/23-a.png',shoe2: '/src/images/shoes-img/women/23-b.png',shoe3: '/src/images/shoes-img/women/23-c.png'}, color: {shoe1: 'skyblue', shoe2: 'blue', shoe3: 'purple'} },
    { id: 24, name: 'Opal Glide', price: 'Rs. 6999', image: {shoe1: '/src/images/shoes-img/women/24-a.png',shoe2: '/src/images/shoes-img/women/24-b.png',shoe3: '/src/images/shoes-img/women/24-c.png'}, color: {shoe1: 'skyblue', shoe2: 'pink', shoe3: 'white'} }
  ];


export default WomenProducts;

