const SportsProducts = [
    { id: 1, name: 'Zenith Sprint', price: 'Rs. 5999' , image: {shoe1: '/src/images/shoes-img/sports/1-a.png',shoe2: '/src/images/shoes-img/sports/1-b.png',shoe3: '/src/images/shoes-img/sports/1-c.png'}, color: {shoe1: 'grey', shoe2: 'black', shoe3: 'green'} },
    { id: 2, name: 'Nova Stride', price: 'Rs. 4600',  image: {shoe1: '/src/images/shoes-img/sports/2-a.png',shoe2: '/src/images/shoes-img/sports/2-b.png',shoe3: '/src/images/shoes-img/sports/2-c.png'}, color: {shoe1: 'skyblue', shoe2: 'blue', shoe3: 'blue'} },
    { id: 3, name: "Apex Rush", price: 'Rs. 8599', image: {shoe1: '/src/images/shoes-img/sports/3-a.png',shoe2: '/src/images/shoes-img/sports/3-b.png',shoe3: '/src/images/shoes-img/sports/3-c.png'}, color: {shoe1: 'purple', shoe2: 'red', shoe3: 'orange'} },
    { id: 4, name: 'Momentum', price: 'Rs. 6500', image: {shoe1: '/src/images/shoes-img/sports/4-a.png',shoe2: '/src/images/shoes-img/sports/4-b.png',shoe3: '/src/images/shoes-img/sports/4-c.png'}, color: {shoe1: 'white', shoe2: 'white', shoe3: 'white'} },
    { id: 5, name: 'Zen Sole', price: 'Rs. 3999', image: {shoe1: '/src/images/shoes-img/sports/5-a.png',shoe2: '/src/images/shoes-img/sports/5-b.png',shoe3: '/src/images/shoes-img/sports/5-c.png'}, color: {shoe1: 'white', shoe2: 'white', shoe3: 'white'} },
    { id: 6, name: 'Velocity Vibe', price: 'Rs. 4600', image: {shoe1: '/src/images/shoes-img/sports/6-a.png',shoe2: '/src/images/shoes-img/sports/6-b.png',shoe3: '/src/images/shoes-img/sports/6-c.png'}, color: {shoe1: 'brown', shoe2: 'blue', shoe3: 'grey'} },
    { id: 7, name: 'Nimbus Dash', price: 'Rs. 2300', image: {shoe1: '/src/images/shoes-img/sports/7-a.png',shoe2: '/src/images/shoes-img/sports/7-b.png',shoe3: '/src/images/shoes-img/sports/7-c.png'}, color: {shoe1: 'yellow', shoe2: 'white', shoe3: 'black'} },
    { id: 8, name: 'Summit Sprint', price: 'Rs. 7599', image: {shoe1: '/src/images/shoes-img/sports/8-a.png',shoe2: '/src/images/shoes-img/sports/8-b.png',shoe3: '/src/images/shoes-img/sports/8-c.png'}, color: {shoe1: 'grey', shoe2: 'black', shoe3: 'blue'} },
    { id: 9, name: 'Radiant Run', price: 'Rs. 6999', image: {shoe1: '/src/images/shoes-img/sports/9-a.png',shoe2: '/src/images/shoes-img/sports/9-b.png',shoe3: '/src/images/shoes-img/sports/9-c.png'}, color: {shoe1: 'black', shoe2: 'black', shoe3: 'blue'} },
    { id: 10, name: 'Eclipse Edge', price: 'Rs. 1599', image: {shoe1: '/src/images/shoes-img/sports/10-a.png',shoe2: '/src/images/shoes-img/sports/10-b.png',shoe3: '/src/images/shoes-img/sports/10-c.png'}, color: {shoe1: 'black', shoe2: 'black', shoe3: 'black'} },
    { id: 11, name: 'Zenith Zest', price: 'Rs. 8999', image: {shoe1: '/src/images/shoes-img/sports/11-a.png',shoe2: '/src/images/shoes-img/sports/11-b.png',shoe3: '/src/images/shoes-img/sports/11-c.png'}, color: {shoe1: 'blue', shoe2: 'red', shoe3: 'black'} },
    { id: 12, name: 'Apex Aura', price: 'Rs. 5999', image: {shoe1: '/src/images/shoes-img/sports/12-a.png',shoe2: '/src/images/shoes-img/sports/12-b.png',shoe3: '/src/images/shoes-img/sports/12-c.png'}, color: {shoe1: 'black', shoe2: 'black', shoe3: 'white'} },
    { id: 13, name: 'Velocity Vortex', price: 'Rs. 4599', image: {shoe1: '/src/images/shoes-img/sports/13-a.png',shoe2: '/src/images/shoes-img/sports/13-b.png',shoe3: '/src/images/shoes-img/sports/13-c.png'}, color: {shoe1: 'red', shoe2: 'white', shoe3: 'blue'} },
    { id: 14, name: 'Nova Nimble', price: 'Rs. 8900', image: {shoe1: '/src/images/shoes-img/sports/14-a.png',shoe2: '/src/images/shoes-img/sports/14-b.png',shoe3: '/src/images/shoes-img/sports/14-c.png'}, color: {shoe1: 'white', shoe2: 'black', shoe3: 'black'} },
    { id: 15, name: 'Summit Surge', price: 'Rs. 999', image: {shoe1: '/src/images/shoes-img/sports/15-a.png',shoe2: '/src/images/shoes-img/sports/15-b.png',shoe3: '/src/images/shoes-img/sports/15-c.png'}, color: {shoe1: 'blue', shoe2: 'black', shoe3: 'black'} },
    { id: 16, name: 'Stride Swift', price: 'Rs. 5699', image: {shoe1: '/src/images/shoes-img/sports/16-a.png',shoe2: '/src/images/shoes-img/sports/16-b.png',shoe3: '/src/images/shoes-img/sports/16-c.png'}, color: {shoe1: 'white', shoe2: 'white', shoe3: 'white'} },
    { id: 17, name: 'Turbo Thrust', price: 'Rs. 9999', image: {shoe1: '/src/images/shoes-img/sports/17-a.png',shoe2: '/src/images/shoes-img/sports/17-b.png',shoe3: '/src/images/shoes-img/sports/17-c.png'}, color: {shoe1: 'black', shoe2: 'blue', shoe3: 'grey'} },
    { id: 18, name: 'Dynamo Dash', price: 'Rs. 8900', image: {shoe1: '/src/images/shoes-img/sports/18-a.png',shoe2: '/src/images/shoes-img/sports/18-b.png',shoe3: '/src/images/shoes-img/sports/18-c.png'}, color: {shoe1: 'white', shoe2: 'grey', shoe3: 'black'} },
    { id: 19, name: 'Aurora Athlete', price: 'Rs. 6900', image: {shoe1: '/src/images/shoes-img/sports/19-a.png',shoe2: '/src/images/shoes-img/sports/19-b.png',shoe3: '/src/images/shoes-img/sports/19-c.png'}, color: {shoe1: 'black', shoe2: 'blue', shoe3: 'white'} },
    { id: 20, name: 'Zenith Zephyr', price: 'Rs. 3200', image: {shoe1: '/src/images/shoes-img/sports/20-a.png',shoe2: '/src/images/shoes-img/sports/20-b.png',shoe3: '/src/images/shoes-img/sports/20-c.png'}, color: {shoe1: 'grey', shoe2: 'black', shoe3: 'black'} },
    { id: 21, name: 'Velocity Vigor', price: 'Rs. 2500', image: {shoe1: '/src/images/shoes-img/sports/21-a.png',shoe2: '/src/images/shoes-img/sports/21-b.png',shoe3: '/src/images/shoes-img/sports/21-c.png'}, color: {shoe1: 'blue', shoe2: 'black', shoe3: 'white'} },
    { id: 22, name: 'Apex Ascent', price: 'Rs. 4500', image: {shoe1: '/src/images/shoes-img/sports/22-a.png',shoe2: '/src/images/shoes-img/sports/22-b.png',shoe3: '/src/images/shoes-img/sports/22-c.png'}, color: {shoe1: 'white', shoe2: 'white', shoe3: 'white'} },
    { id: 23, name: 'Summit Strive', price: 'Rs. 6900', image: {shoe1: '/src/images/shoes-img/sports/23-a.png',shoe2: '/src/images/shoes-img/sports/23-b.png',shoe3: '/src/images/shoes-img/sports/23-c.png'}, color: {shoe1: 'white', shoe2: 'white', shoe3: 'white'} },
    { id: 24, name: 'Dynamo Dart', price: 'Rs. 8900', image: {shoe1: '/src/images/shoes-img/sports/24-a.png',shoe2: '/src/images/shoes-img/sports/24-b.png',shoe3: '/src/images/shoes-img/sports/24-c.png'}, color: {shoe1: 'white', shoe2: 'skin', shoe3: 'blue'} }
  ];

export default SportsProducts;