const SportsProducts = [
  { id: "sports-item1", name: 'Zenith Sprint', price: '5999', image: { shoe1: '/src/images/shoes-img/sports/1-a.png', shoe2: '/src/images/shoes-img/sports/1-b.png', shoe3: '/src/images/shoes-img/sports/1-c.png' }, color: { shoe1: 'grey', shoe2: 'black', shoe3: 'green' } },
  { id: "sports-item2", name: 'Nova Stride', price: '4600', image: { shoe1: '/src/images/shoes-img/sports/2-a.png', shoe2: '/src/images/shoes-img/sports/2-b.png', shoe3: '/src/images/shoes-img/sports/2-c.png' }, color: { shoe1: 'skyblue', shoe2: 'blue', shoe3: 'blue' } },
  { id: "sports-item3", name: "Apex Rush", price: '8599', image: { shoe1: '/src/images/shoes-img/sports/3-a.png', shoe2: '/src/images/shoes-img/sports/3-b.png', shoe3: '/src/images/shoes-img/sports/3-c.png' }, color: { shoe1: 'purple', shoe2: 'red', shoe3: 'orange' } },
  { id: "sports-item4", name: 'Momentum', price: '6500', image: { shoe1: '/src/images/shoes-img/sports/4-a.png', shoe2: '/src/images/shoes-img/sports/4-b.png', shoe3: '/src/images/shoes-img/sports/4-c.png' }, color: { shoe1: 'white', shoe2: 'white', shoe3: 'white' } },
  { id: "sports-item5", name: 'Zen Sole', price: '3999', image: { shoe1: '/src/images/shoes-img/sports/5-a.png', shoe2: '/src/images/shoes-img/sports/5-b.png', shoe3: '/src/images/shoes-img/sports/5-c.png' }, color: { shoe1: 'white', shoe2: 'white', shoe3: 'white' } },
  { id: "sports-item6", name: 'Velocity Vibe', price: '4600', image: { shoe1: '/src/images/shoes-img/sports/6-a.png', shoe2: '/src/images/shoes-img/sports/6-b.png', shoe3: '/src/images/shoes-img/sports/6-c.png' }, color: { shoe1: 'brown', shoe2: 'blue', shoe3: 'grey' } },
  { id: "sports-item7", name: 'Nimbus Dash', price: '2300', image: { shoe1: '/src/images/shoes-img/sports/7-a.png', shoe2: '/src/images/shoes-img/sports/7-b.png', shoe3: '/src/images/shoes-img/sports/7-c.png' }, color: { shoe1: 'yellow', shoe2: 'white', shoe3: 'black' } },
  { id: "sports-item8", name: 'Summit Sprint', price: '7599', image: { shoe1: '/src/images/shoes-img/sports/8-a.png', shoe2: '/src/images/shoes-img/sports/8-b.png', shoe3: '/src/images/shoes-img/sports/8-c.png' }, color: { shoe1: 'grey', shoe2: 'black', shoe3: 'blue' } },
  { id: "sports-item9", name: 'Radiant Run', price: '6999', image: { shoe1: '/src/images/shoes-img/sports/9-a.png', shoe2: '/src/images/shoes-img/sports/9-b.png', shoe3: '/src/images/shoes-img/sports/9-c.png' }, color: { shoe1: 'black', shoe2: 'black', shoe3: 'blue' } },
  { id: "sports-item10", name: 'Eclipse Edge', price: '1599', image: { shoe1: '/src/images/shoes-img/sports/10-a.png', shoe2: '/src/images/shoes-img/sports/10-b.png', shoe3: '/src/images/shoes-img/sports/10-c.png' }, color: { shoe1: 'black', shoe2: 'black', shoe3: 'black' } },
  { id: "sports-item11", name: 'Zenith Zest', price: '8999', image: { shoe1: '/src/images/shoes-img/sports/11-a.png', shoe2: '/src/images/shoes-img/sports/11-b.png', shoe3: '/src/images/shoes-img/sports/11-c.png' }, color: { shoe1: 'blue', shoe2: 'red', shoe3: 'black' } },
  { id: "sports-item12", name: 'Apex Aura', price: '5999', image: { shoe1: '/src/images/shoes-img/sports/12-a.png', shoe2: '/src/images/shoes-img/sports/12-b.png', shoe3: '/src/images/shoes-img/sports/12-c.png' }, color: { shoe1: 'black', shoe2: 'black', shoe3: 'white' } },
  { id: "sports-item13", name: 'Velocity Vortex', price: '4599', image: { shoe1: '/src/images/shoes-img/sports/13-a.png', shoe2: '/src/images/shoes-img/sports/13-b.png', shoe3: '/src/images/shoes-img/sports/13-c.png' }, color: { shoe1: 'red', shoe2: 'white', shoe3: 'blue' } },
  { id: "sports-item14", name: 'Nova Nimble', price: '8900', image: { shoe1: '/src/images/shoes-img/sports/14-a.png', shoe2: '/src/images/shoes-img/sports/14-b.png', shoe3: '/src/images/shoes-img/sports/14-c.png' }, color: { shoe1: 'white', shoe2: 'black', shoe3: 'black' } },
  { id: "sports-item15", name: 'Summit Surge', price: '999', image: { shoe1: '/src/images/shoes-img/sports/15-a.png', shoe2: '/src/images/shoes-img/sports/15-b.png', shoe3: '/src/images/shoes-img/sports/15-c.png' }, color: { shoe1: 'blue', shoe2: 'black', shoe3: 'black' } },
  { id: "sports-item16", name: 'Stride Swift', price: '5699', image: { shoe1: '/src/images/shoes-img/sports/16-a.png', shoe2: '/src/images/shoes-img/sports/16-b.png', shoe3: '/src/images/shoes-img/sports/16-c.png' }, color: { shoe1: 'white', shoe2: 'white', shoe3: 'white' } },
  { id: "sports-item17", name: 'Turbo Thrust', price: '9999', image: { shoe1: '/src/images/shoes-img/sports/17-a.png', shoe2: '/src/images/shoes-img/sports/17-b.png', shoe3: '/src/images/shoes-img/sports/17-c.png' }, color: { shoe1: 'black', shoe2: 'blue', shoe3: 'grey' } },
  { id: "sports-item18", name: 'Dynamo Dash', price: '8900', image: { shoe1: '/src/images/shoes-img/sports/18-a.png', shoe2: '/src/images/shoes-img/sports/18-b.png', shoe3: '/src/images/shoes-img/sports/18-c.png' }, color: { shoe1: 'white', shoe2: 'grey', shoe3: 'black' } },
  { id: "sports-item19", name: 'Aurora Athlete', price: '6900', image: { shoe1: '/src/images/shoes-img/sports/19-a.png', shoe2: '/src/images/shoes-img/sports/19-b.png', shoe3: '/src/images/shoes-img/sports/19-c.png' }, color: { shoe1: 'black', shoe2: 'blue', shoe3: 'white' } },
  { id: "sports-item20", name: 'Zenith Zephyr', price: '3200', image: { shoe1: '/src/images/shoes-img/sports/20-a.png', shoe2: '/src/images/shoes-img/sports/20-b.png', shoe3: '/src/images/shoes-img/sports/20-c.png' }, color: { shoe1: 'grey', shoe2: 'black', shoe3: 'black' } },
  { id: "sports-item21", name: 'Velocity Vigor', price: '2500', image: { shoe1: '/src/images/shoes-img/sports/21-a.png', shoe2: '/src/images/shoes-img/sports/21-b.png', shoe3: '/src/images/shoes-img/sports/21-c.png' }, color: { shoe1: 'blue', shoe2: 'black', shoe3: 'white' } },
  { id: "sports-item22", name: 'Apex Ascent', price: '4500', image: { shoe1: '/src/images/shoes-img/sports/22-a.png', shoe2: '/src/images/shoes-img/sports/22-b.png', shoe3: '/src/images/shoes-img/sports/22-c.png' }, color: { shoe1: 'white', shoe2: 'white', shoe3: 'white' } },
  { id: "sports-item23", name: 'Summit Strive', price: '6900', image: { shoe1: '/src/images/shoes-img/sports/23-a.png', shoe2: '/src/images/shoes-img/sports/23-b.png', shoe3: '/src/images/shoes-img/sports/23-c.png' }, color: { shoe1: 'white', shoe2: 'white', shoe3: 'white' } },
  { id: "sports-item24", name: 'Dynamo Dart', price: '8900', image: { shoe1: '/src/images/shoes-img/sports/24-a.png', shoe2: '/src/images/shoes-img/sports/24-b.png', shoe3: '/src/images/shoes-img/sports/24-c.png' }, color: { shoe1: 'white', shoe2: 'skin', shoe3: 'blue' } }
];

export default SportsProducts;