const MenProduct = [
    { id: 1, name: 'Echo Stride', price: 'Rs. 5999' , image: {shoe1: '/src/images/shoes-img/men/1-a.png',shoe2: '/src/images/shoes-img/men/1-b.png',shoe3: '/src/images/shoes-img/men/1-c.png'}, color: {shoe1: 'blue', shoe2: 'green', shoe3: 'red'} },
    { id: 2, name: 'Nova Step', price: 'Rs. 4600',  image: {shoe1: '/src/images/shoes-img/men/2-a.png',shoe2: '/src/images/shoes-img/men/2-b.png',shoe3: '/src/images/shoes-img/men/2-c.png'}, color: {shoe1: 'grey', shoe2: 'pink', shoe3: 'orange'} },
    { id: 3, name: "Zenith Walk", price: 'Rs. 8599', image: {shoe1: '/src/images/shoes-img/men/3-a.png',shoe2: '/src/images/shoes-img/men/3-b.png',shoe3: '/src/images/shoes-img/men/3-c.png'}, color: {shoe1: 'black', shoe2: 'grey', shoe3: 'brown'} },
    { id: 4, name: 'Aura Tread', price: 'Rs. 6500', image: {shoe1: '/src/images/shoes-img/men/4-a.png',shoe2: '/src/images/shoes-img/men/4-b.png',shoe3: '/src/images/shoes-img/men/4-c.png'}, color: {shoe1: 'black', shoe2: 'brown', shoe3: 'grey'} },
    { id: 5, name: 'Luna Lace', price: 'Rs. 3999', image: {shoe1: '/src/images/shoes-img/men/5-a.png',shoe2: '/src/images/shoes-img/men/5-b.png',shoe3: '/src/images/shoes-img/men/5-c.png'}, color: {shoe1: 'blue', shoe2: 'dark-grey', shoe3: 'white-red'} },
    { id: 6, name: 'Slate Stride', price: 'Rs. 4600', image: {shoe1: '/src/images/shoes-img/men/6-a.png',shoe2: '/src/images/shoes-img/men/6-b.png',shoe3: '/src/images/shoes-img/men/6-c.png'}, color: {shoe1: 'white-red', shoe2: 'white-yellow', shoe3: 'white-black'} },
    { id: 7, name: 'Solstice', price: 'Rs. 2300', image: {shoe1: '/src/images/shoes-img/men/7-a.png',shoe2: '/src/images/shoes-img/men/7-b.png',shoe3: '/src/images/shoes-img/men/7-c.png'}, color: {shoe1: 'white-grey', shoe2: 'white-black', shoe3: 'white'} },
    { id: 8, name: 'Zen Sneak', price: 'Rs. 7599', image: {shoe1: '/src/images/shoes-img/men/8-a.png',shoe2: '/src/images/shoes-img/men/8-b.png',shoe3: '/src/images/shoes-img/men/8-c.png'}, color: {shoe1: 'black-grey', shoe2: 'blue', shoe3: 'black'} },
    { id: 9, name: 'Dusk Dash', price: 'Rs. 6999', image: {shoe1: '/src/images/shoes-img/men/9-a.png',shoe2: '/src/images/shoes-img/men/9-b.png',shoe3: '/src/images/shoes-img/men/9-c.png'}, color: {shoe1: 'orange', shoe2: 'blue', shoe3: 'green'} },
    { id: 10, name: 'Crest Climb', price: 'Rs. 1599', image: {shoe1: '/src/images/shoes-img/men/10-a.png',shoe2: '/src/images/shoes-img/men/10-b.png',shoe3: '/src/images/shoes-img/men/10-c.png'}, color: {shoe1: 'red', shoe2: 'skyblue', shoe3: 'purple'} },
    { id: 11, name: 'Horizon Hue', price: 'Rs. 8999', image: {shoe1: '/src/images/shoes-img/men/11-a.png',shoe2: '/src/images/shoes-img/men/11-b.png',shoe3: '/src/images/shoes-img/men/11-c.png'}, color: {shoe1: 'skyblue', shoe2: 'red', shoe3: 'skin'} },
    { id: 12, name: 'Eon Elevate', price: 'Rs. 5999', image: {shoe1: '/src/images/shoes-img/men/12-a.png',shoe2: '/src/images/shoes-img/men/12-b.png',shoe3: '/src/images/shoes-img/men/12-c.png'}, color: {shoe1: 'grey', shoe2: 'white', shoe3: 'black'} },
    { id: 13, name: 'Summit Stride', price: 'Rs. 4599', image: {shoe1: '/src/images/shoes-img/men/13-a.png',shoe2: '/src/images/shoes-img/men/13-b.png',shoe3: '/src/images/shoes-img/men/13-c.png'}, color: {shoe1: 'purple', shoe2: 'white', shoe3: 'light-blue'} },
    { id: 14, name: 'Dawn Dash', price: 'Rs. 8900', image: {shoe1: '/src/images/shoes-img/men/14-a.png',shoe2: '/src/images/shoes-img/men/14-b.png',shoe3: '/src/images/shoes-img/men/14-c.png'}, color: {shoe1: 'blue', shoe2: 'red', shoe3: 'black'} },
    { id: 15, name: 'Serene Sneak', price: 'Rs. 999', image: {shoe1: '/src/images/shoes-img/men/15-a.png',shoe2: '/src/images/shoes-img/men/15-b.png',shoe3: '/src/images/shoes-img/men/15-c.png'}, color: {shoe1: 'white-black', shoe2: 'black', shoe3: 'blue'} },
    { id: 16, name: 'Alpine Lace', price: 'Rs. 5699', image: {shoe1: '/src/images/shoes-img/men/16-a.png',shoe2: '/src/images/shoes-img/men/16-b.png',shoe3: '/src/images/shoes-img/men/16-c.png'}, color: {shoe1: 'blue-orange', shoe2: 'blue-red', shoe3: 'grey-red'} },
    { id: 17, name: 'Glide Glow', price: 'Rs. 9999', image: {shoe1: '/src/images/shoes-img/men/17-a.png',shoe2: '/src/images/shoes-img/men/17-b.png',shoe3: '/src/images/shoes-img/men/17-c.png'}, color: {shoe1: 'blue', shoe2: 'black', shoe3: 'grey'} },
    { id: 18, name: 'Haven Heel', price: 'Rs. 8900', image: {shoe1: '/src/images/shoes-img/men/18-a.png',shoe2: '/src/images/shoes-img/men/18-b.png',shoe3: '/src/images/shoes-img/men/18-c.png'}, color: {shoe1: 'grey', shoe2: 'black', shoe3: 'blue'} },
    { id: 19, name: 'Twilight Tread', price: 'Rs. 6900', image: {shoe1: '/src/images/shoes-img/men/19-a.png',shoe2: '/src/images/shoes-img/men/19-b.png',shoe3: '/src/images/shoes-img/men/19-c.png'}, color: {shoe1: 'black', shoe2: 'grey', shoe3: 'blue'} },
    { id: 20, name: 'Crest Walk', price: 'Rs. 3200', image: {shoe1: '/src/images/shoes-img/men/20-a.png',shoe2: '/src/images/shoes-img/men/20-b.png',shoe3: '/src/images/shoes-img/men/20-c.png'}, color: {shoe1: 'black', shoe2: 'white', shoe3: 'blue'} },
    { id: 21, name: 'Peak Pace', price: 'Rs. 2500', image: {shoe1: '/src/images/shoes-img/men/21-a.png',shoe2: '/src/images/shoes-img/men/21-b.png',shoe3: '/src/images/shoes-img/men/21-c.png'}, color: {shoe1: 'blue', shoe2: 'white', shoe3: 'white'} },
    { id: 22, name: 'Ember Step', price: 'Rs. 4500', image: {shoe1: '/src/images/shoes-img/men/22-a.png',shoe2: '/src/images/shoes-img/men/22-b.png',shoe3: '/src/images/shoes-img/men/22-c.png'}, color: {shoe1: 'black-red', shoe2: 'black-yellow', shoe3: 'black-blue'} },
    { id: 23, name: 'Echo Tread', price: 'Rs. 6900', image: {shoe1: '/src/images/shoes-img/men/23-a.png',shoe2: '/src/images/shoes-img/men/23-b.png',shoe3: '/src/images/shoes-img/men/23-c.png'}, color: {shoe1: 'white', shoe2: 'grey', shoe3: 'black'} },
    { id: 24, name: 'Haven Stride', price: 'Rs. 8900', image: {shoe1: '/src/images/shoes-img/men/24-a.png',shoe2: '/src/images/shoes-img/men/24-b.png',shoe3: '/src/images/shoes-img/men/24-c.png'}, color: {shoe1: 'light-blue', shoe2: 'green', shoe3: 'blue'} }
  ];

  export default MenProduct;