const MenProduct = [
    { id: "men-item1", name: 'Echo Stride', price: '5999' , image: {shoe1: '/src/images/shoes-img/men/1-a.png',shoe2: '/src/images/shoes-img/men/1-b.png',shoe3: '/src/images/shoes-img/men/1-c.png'}, color: {shoe1: 'blue', shoe2: 'green', shoe3: 'red'} },
    { id: "men-item2", name: 'Nova Step', price: '4600',  image: {shoe1: '/src/images/shoes-img/men/2-a.png',shoe2: '/src/images/shoes-img/men/2-b.png',shoe3: '/src/images/shoes-img/men/2-c.png'}, color: {shoe1: 'grey', shoe2: 'pink', shoe3: 'orange'} },
    { id: "men-item3", name: "Zenith Walk", price: '8599', image: {shoe1: '/src/images/shoes-img/men/3-a.png',shoe2: '/src/images/shoes-img/men/3-b.png',shoe3: '/src/images/shoes-img/men/3-c.png'}, color: {shoe1: 'black', shoe2: 'grey', shoe3: 'brown'} },
    { id: "men-item4", name: 'Aura Tread', price: '6500', image: {shoe1: '/src/images/shoes-img/men/4-a.png',shoe2: '/src/images/shoes-img/men/4-b.png',shoe3: '/src/images/shoes-img/men/4-c.png'}, color: {shoe1: 'black', shoe2: 'brown', shoe3: 'grey'} },
    { id: "men-item5", name: 'Luna Lace', price: '3999', image: {shoe1: '/src/images/shoes-img/men/5-a.png',shoe2: '/src/images/shoes-img/men/5-b.png',shoe3: '/src/images/shoes-img/men/5-c.png'}, color: {shoe1: 'blue', shoe2: 'dark-grey', shoe3: 'white-red'} },
    { id: "men-item6", name: 'Slate Stride', price: '4600', image: {shoe1: '/src/images/shoes-img/men/6-a.png',shoe2: '/src/images/shoes-img/men/6-b.png',shoe3: '/src/images/shoes-img/men/6-c.png'}, color: {shoe1: 'white-red', shoe2: 'white-yellow', shoe3: 'white-black'} },
    { id: "men-item7", name: 'Solstice', price: '2300', image: {shoe1: '/src/images/shoes-img/men/7-a.png',shoe2: '/src/images/shoes-img/men/7-b.png',shoe3: '/src/images/shoes-img/men/7-c.png'}, color: {shoe1: 'white-grey', shoe2: 'white-black', shoe3: 'white'} },
    { id: "men-item8", name: 'Zen Sneak', price: '7599', image: {shoe1: '/src/images/shoes-img/men/8-a.png',shoe2: '/src/images/shoes-img/men/8-b.png',shoe3: '/src/images/shoes-img/men/8-c.png'}, color: {shoe1: 'black-grey', shoe2: 'blue', shoe3: 'black'} },
    { id: "men-item9", name: 'Dusk Dash', price: '6999', image: {shoe1: '/src/images/shoes-img/men/9-a.png',shoe2: '/src/images/shoes-img/men/9-b.png',shoe3: '/src/images/shoes-img/men/9-c.png'}, color: {shoe1: 'orange', shoe2: 'blue', shoe3: 'green'} },
    { id: "men-item10", name: 'Crest Climb', price: '1599', image: {shoe1: '/src/images/shoes-img/men/10-a.png',shoe2: '/src/images/shoes-img/men/10-b.png',shoe3: '/src/images/shoes-img/men/10-c.png'}, color: {shoe1: 'red', shoe2: 'skyblue', shoe3: 'purple'} },
    { id: "men-item11", name: 'Horizon Hue', price: '8999', image: {shoe1: '/src/images/shoes-img/men/11-a.png',shoe2: '/src/images/shoes-img/men/11-b.png',shoe3: '/src/images/shoes-img/men/11-c.png'}, color: {shoe1: 'skyblue', shoe2: 'red', shoe3: 'skin'} },
    { id: "men-item12", name: 'Eon Elevate', price: '5999', image: {shoe1: '/src/images/shoes-img/men/12-a.png',shoe2: '/src/images/shoes-img/men/12-b.png',shoe3: '/src/images/shoes-img/men/12-c.png'}, color: {shoe1: 'grey', shoe2: 'white', shoe3: 'black'} },
    { id: "men-item13", name: 'Summit Stride', price: '4599', image: {shoe1: '/src/images/shoes-img/men/13-a.png',shoe2: '/src/images/shoes-img/men/13-b.png',shoe3: '/src/images/shoes-img/men/13-c.png'}, color: {shoe1: 'purple', shoe2: 'white', shoe3: 'light-blue'} },
    { id: "men-item14", name: 'Dawn Dash', price: '8900', image: {shoe1: '/src/images/shoes-img/men/14-a.png',shoe2: '/src/images/shoes-img/men/14-b.png',shoe3: '/src/images/shoes-img/men/14-c.png'}, color: {shoe1: 'blue', shoe2: 'red', shoe3: 'black'} },
    { id: "men-item15", name: 'Serene Sneak', price: '999', image: {shoe1: '/src/images/shoes-img/men/15-a.png',shoe2: '/src/images/shoes-img/men/15-b.png',shoe3: '/src/images/shoes-img/men/15-c.png'}, color: {shoe1: 'white-black', shoe2: 'black', shoe3: 'blue'} },
    { id: "men-item16", name: 'Alpine Lace', price: '5699', image: {shoe1: '/src/images/shoes-img/men/16-a.png',shoe2: '/src/images/shoes-img/men/16-b.png',shoe3: '/src/images/shoes-img/men/16-c.png'}, color: {shoe1: 'blue-orange', shoe2: 'blue-red', shoe3: 'grey-red'} },
    { id: "men-item17", name: 'Glide Glow', price: '9999', image: {shoe1: '/src/images/shoes-img/men/17-a.png',shoe2: '/src/images/shoes-img/men/17-b.png',shoe3: '/src/images/shoes-img/men/17-c.png'}, color: {shoe1: 'blue', shoe2: 'black', shoe3: 'grey'} },
    { id: "men-item18", name: 'Haven Heel', price: '8900', image: {shoe1: '/src/images/shoes-img/men/18-a.png',shoe2: '/src/images/shoes-img/men/18-b.png',shoe3: '/src/images/shoes-img/men/18-c.png'}, color: {shoe1: 'grey', shoe2: 'black', shoe3: 'blue'} },
    { id: "men-item19", name: 'Twilight Tread', price: '6900', image: {shoe1: '/src/images/shoes-img/men/19-a.png',shoe2: '/src/images/shoes-img/men/19-b.png',shoe3: '/src/images/shoes-img/men/19-c.png'}, color: {shoe1: 'black', shoe2: 'grey', shoe3: 'blue'} },
    { id: "men-item20", name: 'Crest Walk', price: '3200', image: {shoe1: '/src/images/shoes-img/men/20-a.png',shoe2: '/src/images/shoes-img/men/20-b.png',shoe3: '/src/images/shoes-img/men/20-c.png'}, color: {shoe1: 'black', shoe2: 'white', shoe3: 'blue'} },
    { id: "men-item21", name: 'Peak Pace', price: '2500', image: {shoe1: '/src/images/shoes-img/men/21-a.png',shoe2: '/src/images/shoes-img/men/21-b.png',shoe3: '/src/images/shoes-img/men/21-c.png'}, color: {shoe1: 'blue', shoe2: 'white', shoe3: 'white'} },
    { id: "men-item22", name: 'Ember Step', price: '4500', image: {shoe1: '/src/images/shoes-img/men/22-a.png',shoe2: '/src/images/shoes-img/men/22-b.png',shoe3: '/src/images/shoes-img/men/22-c.png'}, color: {shoe1: 'black-red', shoe2: 'black-yellow', shoe3: 'black-blue'} },
    { id: "men-item23", name: 'Echo Tread', price: '6900', image: {shoe1: '/src/images/shoes-img/men/23-a.png',shoe2: '/src/images/shoes-img/men/23-b.png',shoe3: '/src/images/shoes-img/men/23-c.png'}, color: {shoe1: 'white', shoe2: 'grey', shoe3: 'black'} },
    { id: "men-item24", name: 'Haven Stride', price: '8900', image: {shoe1: '/src/images/shoes-img/men/24-a.png',shoe2: '/src/images/shoes-img/men/24-b.png',shoe3: '/src/images/shoes-img/men/24-c.png'}, color: {shoe1: 'light-blue', shoe2: 'green', shoe3: 'blue'} }
  ];

  export default MenProduct;