const Compare = [
  {n:1, id: 'shoe-item1', name: 'Climacool', price: '₹6400' , image: {shoe1: '/src/images/shoes-img/home/1-a.png',shoe2: '/src/images/shoes-img/home/1-b.png',shoe3: '/src/images/shoes-img/home/1-c.png'}, color: {shoe1: 'white-blue', shoe2: 'give', shoe3: 'white-green'} },
  {n:2, id: 'shoe-item2', name: 'Dynablast', price: '₹6500', discountedPrice: '₹4500' , image: {shoe1: '/src/images/shoes-img/home/2-a.png',shoe2: '/src/images/shoes-img/home/2-b.png',shoe3: '/src/images/shoes-img/home/2-c.png'}, color: {shoe1: 'black', shoe2: 'green', shoe3: 'purple'} },
  { n:3,id: 'shoe-item3', name: "Women's Quest", price: '₹6999', image: {shoe1: '/src/images/shoes-img/home/3-a.png',shoe2: '/src/images/shoes-img/home/3-b.png',shoe3: '/src/images/shoes-img/home/3-c.png'}, color: {shoe1: 'brown', shoe2: 'green', shoe3: 'blue'} },
  {n:4, id: 'shoe-item4', name: 'Air Winflo', price: '₹8900', image: {shoe1: '/src/images/shoes-img/home/4-a.png',shoe2: '/src/images/shoes-img/home/4-b.png',shoe3: '/src/images/shoes-img/home/4-c.png'}, color: {shoe1: 'white-red', shoe2: 'give', shoe3: 'give'} },
  { n:5,id: 'shoe-item5', name: 'Edge Lux', price: '₹8999',discountedPrice: '₹6999', image: {shoe1: '/src/images/shoes-img/home/5-a.png',shoe2: '/src/images/shoes-img/home/5-b.png',shoe3: '/src/images/shoes-img/home/5-c.png'}, color: {shoe1: 'skyblue', shoe2: 'green', shoe3: 'dark green'} },
  { n:6,id: 'shoe-item6', name: 'Revolution', price: '₹5900', image: {shoe1: '/src/images/shoes-img/home/6-a.png',shoe2: '/src/images/shoes-img/home/6-b.png',shoe3: '/src/images/shoes-img/home/6-c.png'}, color: {shoe1: 'brown', shoe2: 'red', shoe3: 'green'} },
  { n:7,id: 'shoe-item7', name: 'AlphaBounce', price: '₹4999', image: {shoe1: '/src/images/shoes-img/home/7-a.png',shoe2: '/src/images/shoes-img/home/7-b.png',shoe3: '/src/images/shoes-img/home/7-c.png'}, color: {shoe1: 'white-brown', shoe2: 'white-blue', shoe3: 'white-green'} },
  { n:8,id: 'shoe-item8', name: 'Fluid Flow', price: '₹7999', discountedPrice: '₹5999' , image: {shoe1: '/src/images/shoes-img/home/8-a.png',shoe2: '/src/images/shoes-img/home/8-b.png',shoe3: '/src/images/shoes-img/home/8-c.png'}, color: {shoe1: 'skincolor', shoe2: 'light-green', shoe3: 'baby-pink'} },
  { n:9,id: 'shoe-item4', name: 'Gel Excite', price: '₹8999', image: {shoe1: '/src/images/shoes-img/home/4-b.png',shoe2: '/src/images/shoes-img/home/4-a.png',shoe3: '/src/images/shoes-img/home/4-c.png'}, color: {shoe1: 'give', shoe2: 'white-red', shoe3: 'give'} }
];

export default Compare;